"""
Report Generator Skill — main implementation.

Generates formatted reports (Markdown/HTML) from Pipeline results.
"""

from __future__ import annotations

import json
import logging
from datetime import date, datetime
from supplymind.skills.common.report_generator.schema import ReportInput, ReportOutput

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate analysis reports from Skill outputs."""

    def run(self, input_data: ReportInput | dict) -> ReportOutput:
        if isinstance(input_data, dict):
            params = ReportInput(**input_data)
        else:
            params = input_data

        if params.format == "html":
            content = self._render_html(params.title, params.sections)
        elif params.format == "json":
            content = json.dumps({"title": params.title, "sections": params.sections}, indent=2, ensure_ascii=False)
        else:
            content = self._render_markdown(params.title, params.sections)

        return ReportOutput(
            title=params.title,
            content=content,
            format=params.format,
            section_count=len(params.sections),
            generated_at=date.today().isoformat(),
        )

    def _render_markdown(self, title: str, sections: list[dict]) -> str:
        """Render report as Markdown."""
        lines = [f"# {title}", "", f"*Generated by SupplyMind on {date.today().isoformat()}*", "", "---", ""]

        for section in sections:
            sec_type = section.get("type", "text")
            sec_title = section.get("title", "")
            data = section.get("data", {})

            if sec_type == "summary":
                lines.append(f"## 📊 {sec_title or 'Executive Summary'}")
                lines.append("")
                for k, v in data.items():
                    if isinstance(v, (int, float)):
                        v_str = f"{v:,.2f}" if isinstance(v, float) else f"{v:,}"
                    else:
                        v_str = str(v)
                    lines.append(f"- **{k}**: {v_str}")
                lines.append("")

            elif sec_type == "table":
                lines.append(f"## 📋 {sec_title or 'Data Table'}")
                lines.append("")
                headers = data.get("headers", [])
                rows = data.get("rows", [])
                if headers and rows:
                    lines.append("| " + " | ".join(headers) + " |")
                    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
                    for row in rows[:50]:  # Limit rows
                        cells = [str(c) for c in row]
                        lines.append("| " + " | ".join(cells) + " |")
                    if len(rows) > 50:
                        lines.append(f"*... and {len(rows) - 50} more rows*")
                lines.append("")

            elif sec_type == "forecast":
                lines.append(f"## 📈 {sec_title or 'Demand Forecast'}")
                lines.append("")
                fc_summary = data.get("summary", {})
                for k, v in fc_summary.items():
                    lines.append(f"- **{k}**: {v}")
                forecasts = data.get("forecasts", [])
                if forecasts:
                    lines.append("")
                    lines.append("| SKU | Method | Total | MAPE% | Confidence |")
                    lines.append("|------|--------|-------|-------|------------|")
                    for fc in forecasts[:20]:
                        conf_bar = "█" * int(fc.get("confidence_score", 0) * 8)
                        lines.append(
                            f"| {fc.get('sku_id', '')} | {fc.get('method_used', '')} "
                            f"| {fc.get('total_predicted', 0):.1f} "
                            f"| {fc.get('mape', 0):.1f} | {conf_bar} {fc.get('confidence_score', 0):.0%} |"
                        )
                lines.append("")

            elif sec_type == "reorder":
                lines.append(f"## 🚛 {sec_title or 'Reorder Suggestions'}")
                lines.append("")
                summary = data.get("summary", {})
                lines.append(f"- **Total SKUs**: {summary.get('total_skus', 0)}")
                lines.append(f"- **Need Reorder**: {summary.get('skus_needing_reorder', 0)}")
                lines.append(f"- **High Urgency**: {summary.get('high_urgency_count', 0)}")
                lines.append(f"- **Total Order Qty**: {summary.get('total_order_quantity', 0):,.0f}")
                lines.append(f"- **Est. Cost**: ¥{summary.get('total_estimated_cost', 0):,.2f}")
                lines.append("")

                suggestions = data.get("suggestions", [])
                if suggestions:
                    lines.append("| SKU | Stock | Order Qty | Urgency | Days Left | Reason |")
                    lines.append("|------|-------|-----------|---------|----------|--------|")
                    for sug in suggestions[:15]:
                        urg_icon = {"high": "🔴", "medium": "🟡", "low": "🟢", "none": "⚪"}.get(sug.get("urgency", ""), "⚪")
                        reason = sug.get("reason", "")[:40]
                        lines.append(
                            f"| {sug.get('sku_id', '')} | {sug.get('current_stock', 0):.0f} "
                            f"| {sug.get('suggested_order_qty', 0):.0f} "
                            f"| {urg_icon} {sug.get('urgency', '')} "
                            f"| {sug.get('days_of_stock', 0):.1f} | {reason} ... |"
                        )
                lines.append("")

            elif sec_type == "abcxyz":
                lines.append(f"## 🏷️  {sec_title or 'ABC-XYZ Classification'}")
                lines.append("")
                matrix = data.get("matrix", {})
                if matrix:
                    lines.append("|     | X | Y | Z |")
                    lines.append("|-----|---|---|---|")
                    for row in ["A", "B", "C"]:
                        cells = []
                        for col in ["X", "Y", "Z"]:
                            cell = matrix.get(f"{row}{col}", {})
                            count = cell.get("count", 0) if isinstance(cell, dict) else 0
                            cells.append(str(count))
                        lines.append(f"| {row} | {' | '.join(cells)} |")
                    lines.append("")
                    # Strategies
                    for label in ["AX", "AY", "AZ", "BX", "BY", "BZ", "CX", "CY", "CZ"]:
                        cell = matrix.get(label, {})
                        if isinstance(cell, dict) and cell.get("count", 0) > 0:
                            lines.append(f"- **{label}**: {cell.get('strategy', '')}")
                lines.append("")

            elif sec_type == "anomaly":
                lines.append(f"## ⚠️  {sec_title or 'Anomaly Detection Results'}")
                lines.append("")
                summary = data.get("summary", {})
                lines.append(f"- **Method**: {summary.get('method_used', 'N/A')}")
                lines.append(f"- **Total Anomalies**: {summary.get('total_anomalies_found', 0)}")
                lines.append(f"- **Removal Rate**: {summary.get('removal_rate', 0)}%")
                per_sku = data.get("per_sku_summary", [])
                for sku_sum in per_sku[:10]:
                    if sku_sum.get("anomaly_count", 0) > 0:
                        lines.append(
                            f"- **{sku_sum['sku_id']}**: {sku_sum['anomaly_count']} anomalies "
                            f"({sku_sum['anomaly_pct']}%)"
                        )
                lines.append("")

            else:  # text / default
                lines.append(f"## {sec_title or 'Section'}")
                lines.append("")
                if isinstance(data, str):
                    lines.append(data)
                elif isinstance(data, dict):
                    for k, v in data.items():
                        lines.append(f"- **{k}**: {v}")
                lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Report generated by [SupplyMind](https://github.com/user/supply-mind)*")
        return "\n".join(lines)

    def _render_html(self, title: str, sections: list[dict]) -> str:
        """Render report as HTML."""
        md_content = self._render_markdown(title, sections)
        # Simple markdown-to-HTML conversion (basic)
        html = md_content.replace("# ", "<h1>").replace("\n", "</h1>\n" if "# " in md_content else "\n<br>\n")
        # Wrap in basic template
        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #333; }}
h1 {{ border-bottom: 2px solid #2563eb; padding-bottom: 10px; }}
h2 {{ color: #1e40af; margin-top: 30px; }}
table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f1f5f9; font-weight: 600; }}
tr:nth-child(even) {{ background: #f8fafc; }}
</style></head>
<body>
<pre style="white-space: pre-wrap;">{html}</pre>
</body></html>"""
